### ISSUE TITLE
Getting a noIndex or Index of -1 error in Woods

### ISSUE THREAD

**Issue by bphillab** [SaucedButLeaking/safeDread#9]
I don't know if I have something weird like a relay script messing things up, but right now the script won't run for woods. I was able to fix it in a hacky way by converting Forest to Woods in the zone, but it looks like this is maybe changing something already changed. (ie Woods -> Forest -> Woods)

**Comment by bphillab** [comment]
User Error: Older version installed

**Comment by SaucedButLeaking** [comment]
resolved by https://github.com/SaucedButLeaking/safeDread/commit/b4343c4823cce9b5a21a7799fd8f5610e1096f29
